version: "3.9"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nodebackend-react-frontend
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - nodebackend-react-frontend-network

  api:
    build: ./me-backend/
    ports:
      - "4000:4000"  # Map backend service to port 4000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_DATABASE: nodebackend-react-frontend
    networks:
      - nodebackend-react-frontend-network

  web:
    build: ./me-frontend/
    ports:
      - "3000:3000"  # Map frontend service to port 3000
    environment:
      - VITE_API=http://localhost:3000  # Set the backend API URL
    networks:
      - nodebackend-react-frontend-network

networks:
  nodebackend-react-frontend-network:
    driver: bridge